####################################### USERS #######################################
### GET all users
GET http://localhost:5000/users
### GET user by ID
GET http://localhost:5000/users/5d64e8cde1a4de26c4c6211e
### Create user
POST http://localhost:5000/users
content-type: application/json

{
    "name":"user3",
    "password":"1234567890",
    "email":"user3@mail.com"
}
### Update user
PUT http://localhost:5000/users/5d64e8cde1a4de26c4c6211e
content-type: application/json

{
    "name":"user1",
    "password":"123456789",
    "email":"user1@mail.com"
}

####################################### ORDERS #######################################
### GET all orders
GET http://localhost:5000/orders

### GET one order by ID
GET http://localhost:5000/orders/5d67b0911b39052de8cd9647

### Create an order
POST http://localhost:5000/orders
content-type: application/json

{
  "creator": "5d64e8cde1a4de26c4c6211e",
  "productList": [
    {
      "product": "5d676b42b7d0880b84579f0b",
      "size": "M",
      "itemsCount": 2
    }
  ],
  "deliveryType": "office",
  "deliveryAddress": "",
  "sumToPay": 400,
  "ststus": "inProgress"
}
### Update order
PUT http://localhost:5000/orders/5d67b0911b39052de8cd9647
content-type: application/json

{
  "creator": "5d64e8cde1a4de26c4c6211e",
  "productList": [
    {
      "product": "5d676b42b7d0880b84579f0b",
      "size": "M",
      "itemsCount": 2
    }
  ],
  "deliveryType": "office",
  "deliveryAddress": "",
  "sumToPay": 400,
  "ststus": "inProgress"
}

####################################### PRODUCTS #######################################
### GET all products
GET http://localhost:5000/products
### GET one product by ID
GET http://localhost:5000/products/5d676c3e047df935e0b9486f
### Create product
POST http://localhost:5000/products
content-type: application/json

{
  "sku": 3,
  "name": "Vegeterian",
  "description": "Pizzza without meet",
  "likes": 4.4
}
